version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: ecoeat_db
      POSTGRES_PASSWORD: root
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5455:5432"
volumes:
  postgres: