"""create initial tables

Revision ID: 5d46097accbe
Revises: 
Create Date: 2025-06-16 08:41:19.482481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d46097accbe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clasificacion_materiales',
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('nombre_material', sa.String(), nullable=False),
    sa.Column('tipo_material', sa.String(), nullable=False),
    sa.Column('renovable', sa.Boolean(), nullable=True),
    sa.Column('reciclable', sa.Boolean(), nullable=True),
    sa.Column('impacto_ambiental', sa.String(), nullable=True),
    sa.Column('imagen_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('material_id')
    )
    op.create_table('desempeno_modelo',
    sa.Column('modelo_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('formato', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('dataset', sa.String(), nullable=True),
    sa.Column('fecha_entrenamiento', sa.DateTime(), nullable=True),
    sa.Column('optimizado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('modelo_id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=False),
    sa.Column('registro', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imagenes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre_imagen', sa.String(), nullable=False),
    sa.Column('ruta', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('resultado_modelo', sa.JSON(), nullable=True),
    sa.Column('materiales_renovables', sa.Integer(), nullable=True),
    sa.Column('materiales_no_renovables', sa.Integer(), nullable=True),
    sa.Column('confianza_promedio', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imagenes')
    op.drop_table('usuarios')
    op.drop_table('desempeno_modelo')
    op.drop_table('clasificacion_materiales')
    # ### end Alembic commands ###
